# Generated by Django 6.0.3 on 2026-03-19 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pesaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pes_nro', models.CharField(max_length=80, unique=True)),
                ('fecha_origen_sql', models.DateTimeField(blank=True, null=True)),
                ('id_origen_sql', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('estado_origen_sql', models.CharField(blank=True, max_length=120)),
                ('bse_cod_origen_sql', models.CharField(blank=True, max_length=80)),
                ('modo_origen_sql', models.CharField(blank=True, max_length=40)),
                ('vhc_tip_origen_sql', models.CharField(blank=True, max_length=40)),
                ('comentario_origen_sql', models.TextField(blank=True)),
                ('pes_est', models.CharField(blank=True, max_length=80)),
                ('pes_fec_ing', models.DateTimeField(blank=True, null=True)),
                ('vhc_pat', models.CharField(blank=True, max_length=40)),
                ('pes_tra_nom', models.CharField(blank=True, max_length=255)),
                ('pes_com_cho_nom', models.CharField(blank=True, max_length=255)),
                ('pes_cic_pes_des', models.CharField(blank=True, max_length=255)),
                ('pes_vhc_com_net', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('data_json', models.JSONField(blank=True, default=dict)),
                ('xml_original', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('data_json', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoPesaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdc_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('pdc_doc_nro', models.CharField(blank=True, db_index=True, max_length=80)),
                ('tipo_documento', models.CharField(blank=True, max_length=80)),
                ('fecha_documento', models.DateTimeField(blank=True, null=True)),
                ('origen', models.CharField(blank=True, max_length=255)),
                ('destino', models.CharField(blank=True, max_length=255)),
                ('data_json', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pesaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='camiones.pesaje')),
            ],
        ),
        migrations.CreateModel(
            name='AtributoPesaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pes_att_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('pes_att_val', models.TextField(blank=True)),
                ('data_json', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pesaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='camiones.pesaje')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.CharField(blank=True, db_index=True, max_length=80)),
                ('nombre_producto', models.CharField(blank=True, max_length=255)),
                ('linea', models.CharField(blank=True, max_length=80)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('data_json', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_documento', to='camiones.documentopesaje')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_documento', to='camiones.producto')),
            ],
        ),
    ]
