# Generated by Django 6.0.3 on 2026-03-23 19:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camiones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='ClienteSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80)),
                ('nombre', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='camiones.cliente')),
            ],
            options={
                'ordering': ['cliente', 'codigo'],
                'unique_together': {('cliente', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_uid', models.CharField(help_text='pes_nro para idempotencia', max_length=160, unique=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('estado', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('ANULADO', 'Anulado')], default='CONFIRMADO', max_length=12)),
                ('ciclo', models.CharField(blank=True, max_length=20)),
                ('nro_guia', models.CharField(blank=True, max_length=80)),
                ('fecha_documento', models.DateTimeField(blank=True, null=True)),
                ('patente', models.CharField(blank=True, max_length=40)),
                ('transportista', models.CharField(blank=True, max_length=255)),
                ('chofer', models.CharField(blank=True, max_length=255)),
                ('peso_bruto', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('peso_tara', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('peso_neto', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('observaciones', models.TextField(blank=True)),
                ('data_json', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='camiones.bodega')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='camiones.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('pesaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operaciones', to='camiones.pesaje')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='KardexLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=3, max_digits=18)),
                ('peso', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('stock_anterior', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('stock_posterior', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=18)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kardex_lineas', to='camiones.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kardex_lineas', to='camiones.producto')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='camiones.operacion')),
            ],
            options={
                'ordering': ['operacion', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ClienteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_etruck', models.CharField(max_length=80)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='camiones.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_producto', to='camiones.producto')),
            ],
            options={
                'unique_together': {('cliente', 'codigo_etruck')},
            },
        ),
        migrations.CreateModel(
            name='ClienteBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_default', models.BooleanField(default=False)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='camiones.bodega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='camiones.cliente')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='camiones.clientesucursal')),
            ],
            options={
                'unique_together': {('cliente', 'sucursal', 'bodega')},
            },
        ),
    ]
